name: Python Workflow

on:
  push:
    branches:
      - '*'  # Ovo će pokrenuti workflow na svakoj grani na push događajima
  pull_request:
    branches:
      - '*'  # Ovo će pokrenuti workflow na svakoj grani za pull zahtevima

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.1'  # Zamenite 'x' sa odgovarajućom verzijom Pythona

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Prilagodite prema vašem projektu

    - name: Run Tests
      run: |
        python -m unittest discover -s tests
